### ISSUE TITLE
Getting 504 error when retrieving vaccine card

### ISSUE THREAD

**Issue by hchho** [bcgov/healthgateway#2782]
![image](https://user-images.githubusercontent.com/8084836/132392072-508d487b-27f5-4633-b0dd-a3a970dba486.png)

Both GET request for this URL `https://www.healthgateway.gov.bc.ca/api/immunizationservice/v1/api/Immunization?hdid=xxx` and `https://www.healthgateway.gov.bc.ca/api/immunizationservice/v1/api/AuthenticatedVaccineStatus?hdid=xxx` returns this response:
```<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>```

**Comment by bradhead** [comment]
We have addressed this issue

**Comment by sslaws** [comment]
Closing as resolved.
