### ISSUE TITLE
Vaccine cards can be shared between users

### ISSUE THREAD

**Issue by gabrielbauman** [bcgov/healthgateway#2784]
There is a fundamental design flaw in the vaccine card system.

The QR code issued to vaccinated individuals is generated once and then embedded in a PDF file, which is downloaded by the user to be printed or stored on their smartphone.

**Unfortunately, this means that a valid QR code can be copied and shared with any number of people. Those individuals could then "scan green" whether vaccinated or not.**

- If a "green scan" simply implies the verification of the QR code payload, there's no way to fix this.
- If a "green scan" involves calling a backend endpoint to validate the payload, all you can do is limit the number of green scans per QR code in a short period of time. This means people sharing QR codes might get spurious bad scans, come back in 15 minutes and scan green then.

It would have been better to have a proper smartphone app that generated a new QR code for the user every few seconds.  BOTH the user's session auth token AND a seeded time-based authenticator code AND a nonce to prevent replay attacks should have been used to generate the QR code. A backend API call would be necessary to verify those three items, and biometric auth could restrict access to the app to one person.

Or you could just require a BC service card login every time a user needs to present a QR code, and generate a one-time-use code for each scan.

This would mean that people without smartphones wouldn't be able to use the vaxpass, but they could just print out their vaccination record and carry it with them.

**Comment by cathaloc** [comment]
Figured I'd be more productive moving the conversation from Twitter to here :)

As far as I can tell, the QR code has the user's name and birthday embedded in it, as well as vaccination date/location/lotNumber. The code is digitally signed by http://smarthealthcard.phsa.ca. FHIR standard is being used to transmit this information. https://hl7.org/fhir/

**Comment by gabrielbauman** [comment]
Yep, there are tons of tools to validate and verify the format. Simple walkthrough [here](https://github.com/dvci/health-cards-walkthrough/blob/main/SMART%20Health%20Cards.ipynb).

 The issue is that the generated, signed QR codes are long-lived and can (and will) be shared.

**Comment by cathaloc** [comment]
My understanding is that the QR code must be presented alongside photo ID to confirm it belongs to the user.

**Comment by drewdavies** [comment]
Based on the press conference today, government issued ID is required for validation of the QR code.

https://www.youtube.com/watch?v=rjlfS18Z2bI&t=1163s

**Comment by gabrielbauman** [comment]
So the scanner app will show the name embedded in the QR, and the business will be required to cross-reference with government ID.

That's very slow but it'll work - assuming businesses don't just accept the "green checkmark" on a successful scan in situations where they are processing a lot of people. Like at sporting events.

Guess that's not a software problem though.

**Comment by tehshane** [comment]
At the risk of thread hijacking, is the **public**  key that the JWS is signed with published anywhere?

Mostly out of personal curiosity, but also wondering if there are any contingencies in case the private key is ever leaked. I imagine the impact of cryptographically valid forgeries would be astronomical.

Is key rotation on the radar?

**Comment by drewdavies** [comment]
Based on https://spec.smarthealth.cards/#signing-health-cards, @tehshane, it appears that the public key is stored as part of `/.well-known/jwks.json` via the issuer URL, which in BC's case is: https://smarthealthcard.phsa.ca/v1/issuer/.well-known/jwks.json

Within the same spec document, key rotation is left up to the issuer, but is recommended to be done on an annual basis: https://spec.smarthealth.cards/#key-management

**Comment by tehshane** [comment]
> Based on https://spec.smarthealth.cards/#signing-health-cards, @tehshane, it appears that the public key is stored as part of `/.well-known/jwks.json` via the issuer URL, which in BC's case is: https://smarthealthcard.phsa.ca/v1/issuer/.well-known/jwks.json
> 
> Within the same spec document, key rotation is left up to the issuer, but is recommended to be done on an annual basis: https://spec.smarthealth.cards/#key-management

Excellent! I had tried a `.well-known` URL, but did it under the wrong path. 😅 

I appreciate the response, thank you!

**Comment by bradhead** [comment]
> At the risk of thread hijacking, is the **public** key that the JWS is signed with published anywhere?
> 
> Mostly out of personal curiosity, but also wondering if there are any contingencies in case the private key is ever leaked. I imagine the impact of cryptographically valid forgeries would be astronomical.
> 
> Is key rotation on the radar?

The public key is available as a well-known endpoint as per the Smart Health Card specifications. The private key is secured in vault and is as secure as any other use of public/private key pair or cert signing such as with TLS.

**Comment by nomadicj** [comment]
> > At the risk of thread hijacking, is the **public** key that the JWS is signed with published anywhere?
> > Mostly out of personal curiosity, but also wondering if there are any contingencies in case the private key is ever leaked. I imagine the impact of cryptographically valid forgeries would be astronomical.
> > Is key rotation on the radar?
> 
> The public key is available as a well-known endpoint as per the Smart Health Card specifications. The private key is secured in vault and is as secure as any other use of public/private key pair or cert signing such as with TLS.

Interestingly the Smart Health Card Verifier (https://thecommonsproject.org/smart-health-card-verifier) appears to be looking the public key at https://smarthealthcard.phsa.ca/v1/issuer and failing the issuer verification as a result. Maybe something to check on.

**Comment by sslaws** [comment]
The Smart Health Card Verifier app is not a verifier for the QR codes being returned from Health Gateway which is why it reports that the Issuer (PHSA) is not recognized.  

At this point, I am going to close this issue as I believe that the original discussion has completed.

Thanks
