### ISSUE TITLE
release only on Google play store

### ISSUE THREAD

**Issue by nutpantz** [bcgov/healthgateway#2798]
Some people don't agree with the google terms of service, to use Google play store the releases should be available on the amazon store,github  and also on fdroid. (It would also be good if all open source government apps had their own fdroid repository)

**Comment by sslaws** [comment]
@nutpantz I've forwarded this request onto the team responsible for the Verifier App.

**Comment by nutpantz** [comment]
What about the personal app?

On September 11, 2021 12:23:08 PM PDT, Stephen Laws ***@***.***> wrote:
***@***.*** I've forwarded this request onto the team responsible for the

**Comment by sslaws** [comment]
@nutpantz what personal app are you referring to?

**Comment by nutpantz** [comment]
Bc services card app

On September 11, 2021 12:31:48 PM PDT, Stephen Laws ***@***.***> wrote:
***@***.*** what personal app are you referring to?

**Comment by sslaws** [comment]
I can pass the request on to that team as well if you'd like?

**Comment by nutpantz** [comment]
It looked like this was the repository for that app, can you point me to the repository for that app and I'll post the issue there. If there is none please forward the issue.

**Comment by sslaws** [comment]
> It looked like this was the repository for that app, can you point me to the repository for that app and I'll post the issue there. If there is none please forward the issue.
> […](#)

I'm not aware of the repository so I'll forward on and if I get any repo info will post a followup here.

**Comment by nutpantz** [comment]
I'm very interested in using the health gateway wtb site but I don't use Google play and I'm concerned that I can't access my health records without agreeing to Google play to use the app.

**Comment by sslaws** [comment]
I will take that comment to our management team as well.

**Comment by nutpantz** [comment]
Great, it would be a horrible day when you only get access to government services only if you agree to Google or apples terms of services before first.

**Comment by sslaws** [comment]
Information has been relayed to the other teams, marking as closed.
