### ISSUE TITLE
Save to Apple/Google Pay apps

### ISSUE THREAD

**Issue by tehshane** [bcgov/healthgateway#2807]
**Is your feature request related to a problem? Please describe.**
As the vaccine mandate rolls out, there is some confusion and frustration about how to save and recall the QR codes without needing to go through the Health Gateway flow every time. Workarounds include printing out the cards, taking screenshots, or downloading PDFs, but these solutions present their own challenges and are not always accessible for technically challenged people nor convenient for everyone.

**Describe the solution you'd like**
When accessing the QR code on Health Gateway on a mobile device, consider offering the option to save the code as a card to Apple Pay, Google Pay, and if available, other major vendors like Samsung Pay (assuming they offer the means to do so). These apps often include convenience features for users that reduce friction around finding and presenting their cards at points of service.

**Describe alternatives you've considered**
As above, alternatives do exist in the form of screenshots, printouts, and PDFs. Other more involved alternatives include using 3rd party apps such as _Pass2Pay_ for Android and _Pass2U Wallet_ for iOS. These are effective, but encourage people to pass their health information through untrusted apps outside of PHSA's bubble. This isn't ideal.

**Additional context**
Samples of other apps offering this functionality are attached, as is a concept of what the card would look like in Google Pay on Android.

Thank you!

![Screenshot_20210914-131801](https://user-images.githubusercontent.com/3360089/133328361-b8cf4642-ca0c-4f9b-a4bf-1f3a378d9719.png)
![Screenshot_20210914-131708](https://user-images.githubusercontent.com/3360089/133328363-1c92dd28-0a46-4e99-88dc-c955c60131d3.png)

**Comment by tehshane** [comment]
Additional information for Android:  
https://developers.google.com/pay/passes/guides/pass-verticals/use-cases?vertical=covid-cards#pass-vertical

**Comment by sslaws** [comment]
Closing as obsolete at this point.  iOS devices were able to add to the wallet with after Apple released an update.  I'm not sure that Google devices did though.
