### ISSUE TITLE
Date of Birth formatting error on COVID-19 Vaccination Record

### ISSUE THREAD

**Issue by tonymitchell** [bcgov/healthgateway#5765]
**Describe the bug**
Date of Birth shows some JSON data instead of a nicely formatted date.

**To Reproduce**

1. Go to 'BC Vaccine Card'
2. Click on '>' to show details
3. Look at Date of Birth field.
4. See display error

Happens on both desktop and phone.

**Expected behavior**
Date of Birth should contain a nicely formatted date value.

**Screenshots**
![image](https://github.com/bcgov/healthgateway/assets/1694080/99786446-0ac0-4b21-9cd4-202d00447fc5)

**Desktop (please complete the following information):**

-   OS: Windows 11
-   Browser: Chrome
-   Version: 118.0.5993.118

**Smartphone (please complete the following information):**

-   Device: Samsung Galaxy S23
-   OS: Android
-   Browser: Chrome

**Comment by ninosamson** [comment]
Thanks for raising this @tonymitchell.
