### ISSUE TITLE
Trusted device name should use local info rather than authenticating device

### ISSUE THREAD

**Issue by gjlawran** [bcgov/healthgateway#713]
**Describe the bug**
When attempting to establish a browser on my MacBook as a trusted device the default device name provided by the app uses that of the mobile device used to enrol (Galaxy S8) rather than the new trusted device (Fred's Macbook).

**To Reproduce**
Steps to reproduce the behaviour:
1. In the browser visit https://www.healthgateway.gov.bc.ca/
2. press login button 
3. This directs user to https://id.gov.bc.ca/login/entry#start 
5. Select Already Setup - Use a Mobile card
6  Open app and enter pairing code.
7. Bowser redirects to https://id.gov.bc.ca/login/entry# 
8. Do you want to remember? Name this device prompts with "Galaxy S8" rather than info about the device being enrolled that is available  (See https://www.deviceinfo.me/ ).

**Expected behaviour**
I expect the device name field to default to something like "Chrome on macOS" .

**Screenshots**

**Desktop (please complete the following information):**
- OS: macOS version 10.15.5 (32-bit) 
- Browser: Chrome 
- Version : version 84.0.4147.105 (32-bit)

**Comment by ninosamson** [comment]
Thank you for raising this issue. It appears to be related to the BC Services Card Identity Assurance Service.  Please contact the [BC Services Card helpdesk](https://www2.gov.bc.ca/gov/content/governments/government-id/bc-services-card/log-in-with-card/get-help).

We are committed to improving the Health Gateway for BC residents. If you have any feedback or suggestions, please contact healthgateway@gov.bc.ca
